# This is a basic workflow to help you get started with Actions

name: Main CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths-ignore:
      - "package.json"
      - "CHANGELOG.md"
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy-qa:
    if: "contains(github.event.commits[0].message, '[qa]')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
      - name: build qa version
        run: |
          yarn install
          yarn run build:qa
      - name: Deploy to qa
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
      - name: version update
        uses: remorses/bump-version@js
        with:
          version_file: ./VERSION
          prerelease_tag: alpha
          ignore: dist, ignored_folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-and-deploy-stage:
    if: "contains(github.event.commits[0].message, '[stage]')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
      - name: build stage version
        run: |
          yarn install
          yarn run build:stage
      - name: deploy to stage
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
      - name: Bump version and push tag
        uses: TriPSs/conventional-changelog-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN_ACTION }}
          git-message: "chore(release): {version}"
          preset: "angular"
          tag-prefix: ""
          output-file: "CHANGELOG.md"
      - name: version update
        uses: remorses/bump-version@js
        with:
          version_file: ./VERSION
          prerelease_tag: beta
          ignore: dist, ignored_folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
